import {useState} from 'react';
import {Search,X,ArrowRight,ClipboardList,Building2,Store,Package} from 'lucide-react';
import {PageHeader} from '../components/layout/PageHeader';
import {PORTAL_ORDERS,SUPPLIER_STORES} from '../data/portalData';
import {useDemoData} from '../context/DemoDataContext';
const titles:Record<string,string>={dashboard:'Dashboard',orders:'Orders',deal_orders:'Deal Orders',order_packages:'Order Packages',faqs:'Q&A',string_processor:'String Processor',areas:'Areas'};
const FAQS=[['How do I review a medicine mapping?','Open Medicine Management, choose Medicine Mappings, compare the supplier product with the suggested match, then accept or select an alternative.'],['Can a pharmacist reject a voice suggestion?','Yes. The pharmacy app lets the pharmacist change quantities or reject individual suggestions before adding accepted items to the cart.'],['How are supplier minimum charges applied?','Each supplier store has a minimum order charge. The demo displays sample values in EGP.'],['Where can I find mapping changes?','Mapping Logs shows previous and new products, the reviewer, date and reason.'],['Are these real orders or AI outputs?','All records and workflows are simulated. No supplier order is sent and no microphone recording is made.']];
const AREAS=[['Nasr City','Cairo',18,6],['Heliopolis','Cairo',12,4],['Maadi','Cairo',9,4],['Haram & Faisal','Giza',15,5],['6th of October','Giza',11,3],['Sidi Gaber','Alexandria',8,4],['Mansoura Central','Dakahlia',10,3]];
export function PortalPage({screen,onNavigate}:{screen:string;onNavigate:(screen:string)=>void}){
 const {pharmacies}=useDemoData();const [search,setSearch]=useState('');const [status,setStatus]=useState('all');const [page,setPage]=useState(1);const [selected,setSelected]=useState<typeof PORTAL_ORDERS[number]|null>(null);const [question,setQuestion]=useState<number|null>(0);const [text,setText]=useState('بنادول اكسترا 24 قرص (س 48.00)\nكونكور 5 مجم 30 قرص (ك 2)');const [result,setResult]=useState('');
 const filtered=PORTAL_ORDERS.filter(order=>(screen!=='deal_orders'||order.type==='Deal')&&(screen!=='order_packages'||order.type==='Package')&&`${order.id} ${order.pharmacy} ${order.supplier}`.toLowerCase().includes(search.toLowerCase())&&(status==='all'||order.status===status));
 const totalPages=Math.max(1,Math.ceil(filtered.length/10));const current=Math.min(page,totalPages);const visible=screen==='dashboard'?PORTAL_ORDERS.slice(0,6):filtered.slice((current-1)*10,current*10);
 return <div className="pb-10"><PageHeader title={titles[screen]||'Dashboard'} breadcrumbs={screen==='dashboard'?['Dashboard']:['Dashboard',titles[screen]]}/><div className="p-4 sm:p-6 space-y-5">
 {screen==='dashboard'&&<><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{[{label:'Orders',count:PORTAL_ORDERS.length,icon:ClipboardList,to:'orders',color:'bg-[#39b6ed]'},{label:'Pharmacies',count:pharmacies.length,icon:Store,to:'pharmacies',color:'bg-[#78d4a3]'},{label:'Suppliers',count:SUPPLIER_STORES.length,icon:Building2,to:'suppliers',color:'bg-[#8e66ec]'},{label:'Order Packages',count:PORTAL_ORDERS.filter(order=>order.type==='Package').length,icon:Package,to:'order_packages',color:'bg-[#f5c94c]'}].map(card=><button key={card.label} onClick={()=>onNavigate(card.to)} className={`${card.color} text-white p-5 rounded-md flex justify-between items-center text-left`}><span><strong className="text-2xl block">{card.count}</strong><span className="text-xs mt-1 block">{card.label}</span></span><card.icon size={27}/></button>)}</div><div className="flex justify-between items-center"><h2 className="text-sm font-semibold">Recent Orders</h2><button onClick={()=>onNavigate('orders')} className="text-xs text-sky-600 flex gap-1 items-center">View all <ArrowRight size={13}/></button></div></>}
 {['dashboard','orders','deal_orders','order_packages'].includes(screen)&&<div className="bg-white border rounded-md overflow-hidden">{screen!=='dashboard'&&<div className="p-4 flex flex-wrap justify-between gap-3 border-b"><div className="relative w-72"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><input aria-label="Search orders" className="cluster-input pl-9" placeholder="Search order, pharmacy or supplier..." value={search} onChange={event=>{setSearch(event.target.value);setPage(1);}}/></div><select aria-label="Order status" className="cluster-input w-auto" value={status} onChange={event=>{setStatus(event.target.value);setPage(1);}}><option value="all">All statuses</option>{['Pending','Confirmed','Preparing','Delivered','Cancelled'].map(value=><option key={value}>{value}</option>)}</select></div>}<div className="overflow-x-auto"><table className="w-full text-xs text-left"><thead className="bg-slate-50 text-slate-400 text-[10px] uppercase"><tr>{['Order ID','Pharmacy','Supplier','Created','Items','Total','Status'].map(label=><th className="p-4" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y divide-dashed divide-slate-100">{visible.map(order=><tr key={order.id} className="hover:bg-slate-50"><td className="p-4"><button className="text-sky-600 font-semibold" onClick={()=>setSelected(order)}>{order.id}</button></td><td className="p-4">{order.pharmacy}</td><td className="p-4">{order.supplier}</td><td className="p-4 whitespace-nowrap text-slate-500">{order.created}</td><td className="p-4">{order.items}</td><td className="p-4 whitespace-nowrap">{order.total.toLocaleString('en-US',{minimumFractionDigits:2})} EGP</td><td className="p-4"><span className={`rounded px-2 py-1 text-[10px] ${order.status==='Delivered'?'bg-emerald-50 text-emerald-600':order.status==='Cancelled'?'bg-rose-50 text-rose-500':'bg-sky-50 text-sky-600'}`}>{order.status}</span></td></tr>)}{!visible.length&&<tr><td colSpan={7} className="p-12 text-center text-slate-400">No orders match your search.</td></tr>}</tbody></table></div>{screen!=='dashboard'&&<div className="flex justify-between p-4 text-xs border-t text-slate-500"><span>{filtered.length} orders · Mock data</span><div className="flex gap-4"><button disabled={current===1} onClick={()=>setPage(current-1)}>Previous</button><span>{current} / {totalPages}</span><button disabled={current===totalPages} onClick={()=>setPage(current+1)}>Next</button></div></div>}</div>}
 {screen==='faqs'&&<section className="bg-white border rounded-md p-5 max-w-4xl">{FAQS.map(([title,answer],index)=><div className="border-b last:border-0 py-4" key={title}><button aria-expanded={question===index} onClick={()=>setQuestion(question===index?null:index)} className="text-sm font-semibold w-full text-left flex justify-between">{title}<span className="text-sky-600">{question===index?'−':'+'}</span></button>{question===index&&<p className="text-xs leading-relaxed text-slate-500 mt-3">{answer}</p>}</div>)}</section>}
 {screen==='areas'&&<section className="bg-white border rounded-md overflow-hidden"><div className="p-4 border-b"><input aria-label="Search areas" placeholder="Search area or governorate..." className="cluster-input max-w-xs" value={search} onChange={event=>setSearch(event.target.value)}/></div><div className="overflow-x-auto"><table className="w-full text-xs text-left"><thead className="bg-slate-50 text-slate-400"><tr>{['Area','Governorate','Pharmacies','Suppliers'].map(label=><th className="p-4" key={label}>{label}</th>)}</tr></thead><tbody>{AREAS.filter(row=>row.join(' ').toLowerCase().includes(search.toLowerCase())).map(row=><tr className="border-t" key={row[0]}>{row.map((value,index)=><td className="p-4" key={index}>{value}</td>)}</tr>)}</tbody></table></div><p className="p-4 text-[10px] text-slate-400">Sample district coverage. Aggregated figures are illustrative.</p></section>}
 {screen==='string_processor'&&<section className="bg-white border rounded-md p-5 space-y-4 max-w-4xl"><div><h2 className="font-semibold text-sm">Supplier catalogue text cleanup</h2><p className="text-xs text-slate-400 mt-1">Mock processing: remove supplier price/quantity tags and normalize spacing. No AI model is called.</p></div><label className="text-xs text-slate-500 block">Supplier text<textarea aria-label="Supplier text" dir="auto" className="cluster-input min-h-36 mt-2" value={text} onChange={event=>setText(event.target.value)}/></label><button disabled={!text.trim()} className="cluster-button" onClick={()=>setResult(text.replace(/\([^)]*\)/g,'').split('\n').map(line=>line.trim().replace(/\s+/g,' ')).filter(Boolean).join('\n'))}>Process text</button>{result&&<div><h3 className="text-xs font-semibold mb-2">Cleaned product names</h3><pre dir="auto" className="whitespace-pre-wrap bg-sky-50 p-4 rounded text-xs font-arabic">{result}</pre><button onClick={()=>onNavigate('mappings')} className="text-xs text-sky-600 mt-3">Open Medicine Mappings →</button></div>}</section>}
 </div>{selected&&<div className="fixed inset-0 z-50 bg-slate-900/40 flex items-center justify-center p-4"><section role="dialog" aria-modal="true" aria-label="Order details" className="bg-white rounded-lg p-5 w-full max-w-md"><div className="flex justify-between mb-4"><h2 className="font-semibold">{selected.id}</h2><button aria-label="Close order details" onClick={()=>setSelected(null)}><X size={18}/></button></div>{Object.entries(selected).map(([key,value])=><div key={key} className="flex justify-between gap-4 text-xs border-b py-2"><span className="capitalize text-slate-400">{key}</span><span>{value}</span></div>)}<p className="text-[10px] text-slate-400 mt-3">Mock order details. No external order is placed.</p></section></div>}</div>;
}
