import {useState} from 'react';
import {Search,MoreHorizontal,X,Filter} from 'lucide-react';
import {PageHeader} from '../components/layout/PageHeader';
import {useDemoData} from '../context/DemoDataContext';
import {SUPPLIER_STORES} from '../data/portalData';
const money=(value:number)=>value.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
export function SupplierStoresPage(){
  const {supplierStores:rows,toggleSupplierStoreStatus}=useDemoData();
  const [search,setSearch]=useState('');const [status,setStatus]=useState('all');const [detail,setDetail]=useState<typeof SUPPLIER_STORES[number]|null>(null);
  const filtered=rows.filter(row=>`${row.storeName} ${row.supplierName}`.toLowerCase().includes(search.toLowerCase())&&(status==='all'||row.status===status));
  const toggleStatus=(id:string)=>{toggleSupplierStoreStatus(id);setDetail(null);};
  return <div className="pb-8"><PageHeader title="Suppliers" breadcrumbs={['Dashboard','Suppliers']} actionSlot={    <div className="flex flex-wrap items-center justify-between gap-3 "><div className="relative w-64"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><input aria-label="Search suppliers" placeholder="Search suppliers ..." className="cluster-input pl-9" value={search} onChange={event=>setSearch(event.target.value)}/></div><div className="flex gap-2 items-center"><Filter size={14} className="text-slate-400"/><select aria-label="Supplier status" className="cluster-input" value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All statuses</option><option>Approved</option><option>Blocked</option></select></div></div>}/><div className="p-4 sm:p-6"><div className="bg-white rounded-sm shadow-sm border border-slate-100">

    <div className="overflow-x-auto"><table className="w-full text-left text-[11px] min-w-[1000px]"><thead className="text-[10px] uppercase text-[#a9aebb]"><tr>{['Store name','Supplier name','Quantity updated at','Total','Invoices','Type','Minimum charge','Status','Actions'].map(label=><th key={label} className="font-semibold px-4 py-3 whitespace-nowrap">{label}</th>)}</tr></thead><tbody>{filtered.map(row=><tr key={row.id} className="border-t border-dashed border-slate-100 hover:bg-slate-50"><td className="px-4 py-[6px] whitespace-nowrap"><button onClick={()=>setDetail(row)} className="flex items-center gap-2 font-semibold text-[#16a2d5]"><span className={`w-2.5 h-2.5 rounded-full shadow-sm ${row.connection==='online'?'bg-[#13bd91]':row.connection==='busy'?'bg-[#ff474f]':'bg-[#9ba3af]'}`}/>{row.storeName}</button></td><td className="px-4 py-[6px] text-slate-700 font-arabic"><span dir="rtl">{row.supplierName}</span></td><td className="px-4 py-[6px]"><span className={`text-[10px] font-semibold px-2 py-0.5 rounded-sm whitespace-nowrap ${row.recent&&row.updated!=='Not updated'?'bg-[#ecfcf2] text-[#53c693]':'bg-[#fff0f5] text-[#e96395]'}`}>{row.updated}</span></td><td className="px-4 py-[6px] font-semibold text-slate-700">{money(row.total)}</td><td className="px-4 py-[6px] font-semibold text-slate-700">{row.invoices}</td><td className="px-4 py-[6px] font-semibold text-slate-700">{row.type}</td><td className="px-4 py-[6px] font-semibold text-slate-700 whitespace-nowrap">{money(row.minimumCharge)} EGP</td><td className="px-4 py-[6px]"><span className={`px-2 py-0.5 rounded-sm text-[10px] font-semibold ${row.status==='Approved'?'bg-[#ecfcf2] text-[#53c693]':'bg-[#fff0f5] text-[#e96395]'}`}>{row.status}</span></td><td className="px-4 py-[6px] text-center"><button aria-label={`Actions for ${row.storeName}`} onClick={()=>setDetail(row)} className="text-slate-400 p-1"><MoreHorizontal size={15}/></button></td></tr>)}{!filtered.length&&<tr><td colSpan={9} className="p-12 text-center text-slate-400">No suppliers match your filters.</td></tr>}</tbody></table></div><div className="border-t px-5 py-3 text-[11px] text-slate-400">Showing {filtered.length} of {rows.length} suppliers · Mock data</div>
  </div></div>{detail&&<div className="fixed inset-0 z-50 bg-slate-900/40 flex items-center justify-center p-4"><section role="dialog" aria-modal="true" aria-label="Supplier details" className="bg-white rounded-lg p-5 max-w-md w-full"><div className="flex justify-between mb-4"><h2 className="font-semibold">{detail.storeName}</h2><button aria-label="Close supplier details" onClick={()=>setDetail(null)}><X size={18}/></button></div><div className="grid grid-cols-2 gap-4 text-xs mb-5">{[['Supplier',detail.supplierName],['Type',detail.type],['Status',detail.status],['Invoices',detail.invoices],['Minimum charge',`${money(detail.minimumCharge)} EGP`],['Total',`${money(detail.total)} EGP`]].map(([label,value])=><div key={label}><span className="block text-slate-400 mb-1">{label}</span><strong dir="auto">{value}</strong></div>)}</div><button className="cluster-button" onClick={()=>toggleStatus(detail.id)}>{detail.status==='Approved'?'Block supplier':'Approve supplier'}</button><p className="text-[10px] text-slate-400 mt-3">Fictional supplier record. Changes affect this demo only.</p></section></div>}</div>;
}
